# ......................... MMMMMM............................
# ........................MM7III77NMM.........................
# ............. .MMMMMM .MMM....77777MM ......................
# ............MMN..MMIMMMMM.OOZI $$$77MM......................
# .......... MN...7MMMMMMMM,.8:O.$$$$$$$M.....................
# ...........M.,,:MMMM8$$$$$$$MOM$$$$$$$$M ...................
# ...........MM,.= MMMMMMMD$$$ZZZMN$$$$$$MM...................
# ............M+,,,,,,.MMN~~MN$ZZOONN$$$$$MD..................
# .............MMMM..,+M+M~~~~:NM$OO8M$$$$$M+.................
# .............MM..M?~~~~M~~~:M~~~~DMMM$$$$$DMM...............
# ..............:MM~=~~~~~~~~MM~~~~~~M8M$$$$$$M...............
# ................M~=~~~~~~~~~~~~~~MM88NMMMNZZM ..............
# ................M=+==~~~~~~~MMM~~N88M~~~==MMM ..............
# ................ MM:~~~=MDDDDDM?~:MM~~M~~=~M ...............
# ..................MMDDDDDDDDMM+~~~~~~7~~~=:M................
# .................. MMMMDDDDDM?~~~~~~~~~~~~M ................
# ....................MZM~M8ZZM==~~~~MOMMMMM..................
# .....................MM$M$MD=+=~=MMMMMMMM...................
# .............MMMMM... MM7MMMMMMMOM$$$$ZO$MM.. ..............
# ...........8MM$$Z$MMMMM7M$$M777NOO8MD$$ZNM~.MM..............
# ..........MMMZZZZZZMM~N777MMM77NZOO8$MM ....~MM ............
# ..........MDMOOOOOOM=8777M===M7DZOO88NMI.....,.MN...........
# ..........MM:DOOOOOMM$777M??IM777MMNM$.....,.M..M...........
# .......... MM:OOOOOOM77777NMN77777$$$M:....M....M...........
# ............MMNOOOOOMN777777777$$$ZMMMD,M.....,MM...........
# ............~M~M888OMMM$$$$$$$$ZOMM88OOM.~::: MM ...........
# .............MMMMMMMM.MMN7ZZZZOOMMODZZZZZMMMMM..............
# ................  . ..  MMMMMMMMMMOZZZZZZMMM ...............
# ...........................  .. .MZZZZZZZM:M................
# .................................MM$ZZZZZ8:M+...............
# ..................................M7$ZZZZO~M................
# ..................................MM7$$$$MMM ...............
# ....................................MMMMM ..................

require 'uuidtools'
require 'base64'


class Map < ActiveRecord::Base

  MAX_TEXT_RENDER_LEN = 260
  MAX_NAME_RENDER_LEN = 50

  # Core components	
  attr_accessible :name, :slug, :text, :thumbnail

  # For quick rendering of item counts
  attr_accessible :resources_count, :standards_count, :objectives_count

  has_and_belongs_to_many :course_subjects, :uniq => true, :order => 'name ASC'
  has_and_belongs_to_many :course_grades, :uniq => true, :order => 'id ASC'
  has_many :map_standards

  belongs_to :user

  validates :user, :presence => {:message => 'cannot be missing.'}
  validates :name, :presence => {:message => 'cannot be blank.'}, :length => {:minimum => 2, :maximum => 250}
  validates :text, :presence => {:message => 'cannot be blank.'}, :length => {:minimum => 2, :maximum => 2048}
  validates_uniqueness_of :slug, :allow_nil => true, :case_sensitive => true

  before_create :default_values
  before_validation	:clean_attrs

  def to_param
	  self.slug
  end

  private 

  def clean_attrs
    if self.name then self.name = self.name.strip end
    if self.text then self.text = self.text.strip end
  end

  def default_values
    self.slug ||= (Base64.strict_encode64 UUIDTools::UUID.random_create).downcase
  
    self.resources_count  ||= 0
    self.standards_count  ||= 0
    self.objectives_count ||= 0
  end
  
end

