
#       .................... ......... ..... .  ..   . ~DMMMMMM$,.    ....   .  . .    .................... ..............
# ..  ...................... ...................  .ZMMMMMMMMMMMMMMMMM,..  ................................................
#     .. ...................................... .MMMMMMMMMMMMMMMMMMMMMMMM.................................................
#  . ......................................... MMMMMMMMZ77777777ZMMMMMMMMMM8,.............................................
#     .......................................,MMMMMN77777777777777777OMMMMMMMM,  .........................................
#   .....................7MMMM8.............:MMMMM777777777777777777777$OMMMMMMM+.........................................
#   .   ......... .. .,MMMMMMMMMM8 . .......MMMMN77INMMMNMMMMM7$7$$$7$$$777MMMMMMM........................................
# ... ........    .+OMMMMMMMMMMMMMM.. ... .MMMMN77MM...,. ...,MM$$$$$$$$$$$7$MMMMMMN......................................
#       .... ..MMMMMMMMMMM...:MMMMMMM+ ...8MMMM7OM~...OO.. . ..=MO$$$$$$$$$$$$7MMMMMM,  ..................................
#     ....  NMMMMMMMMMM8.....DMMMMMMMMMM..MMMM$OM....OOO~...OO...M7$$$$$$$$$$$$$OMMMMMN  .................................
#    .....~MMMMMMMD.......MMMMMMMMMMMMMMMIMMMM7M~...OOOOO.8OOO...7M$$$$$$$$$$$$$$7MMMMMM. ................................
#       .MMMMMM+,......,MMMI..,::,,. MMMMMMMM$$M...OOO$OOOOOOO....MZ$$$$$$$$$$$$$$7NMMMMM ................................
#     ..MMMMMM,,.......$MM.==:~ZMMMMMMMMMMMMM$NM..OOO:,OOO88OO....MN$$$$$$$$$$$$$$$$8MMMMM................................
# . . .NMMMM:.........,MMMMMMMMMMMMMMMMMMMMMMMMM..7O8..~8,.OOO.. .M8$$$$$$$$$$$$$$$$$ZMMMMM...............................
#      MMMMN.........,:MMMMMMNZZ$$ZZZZZZZ$$$Z$8MMMMMM,.....OOO...,M$$ZZZ$ZZ$$$$$$$$$$$ZMMMMM .............................
#  . .+MMMM.........,,MMMMZZZZZ$$Z$$ZZ$Z$Z$$ZZZZ$Z$ZNMMMM=.7:....MD$$$$$$$ZZZZ$$$$$$$$$ZMMMMM.............................
#    .ZMMMM,.,,,,,,,::MMMMMMMMMMMNZ$$Z$ZZZZZ$$$$$$$$Z$ZZZMMMM$..MMZZ$$$$$$$$$$ZZZ$$$$$$$ZMMMMN ...........................
#     IMMMM ..,:::~~,.MMMMMMMMMMMMMMMMMD$ZZZZZ$Z$$$$$$$$ZZZZDMMMMZ$$ZZ$$$$$$$$ZZZ$$$$$$$$OMMMMI...........................
#     .MMMM$..~M7,=NMMMMMMMMMMMMMMMMMMMMMMMD$ZZZ$$$$$$$ZZZZZZZZ8MMMM$ZZ$$$$$$$$$$$$ZZ$$$$$MMMMM ..........................
#     .MMMMM.....DMMM?...NMMMMMMMMMMMMMMMMMMMMM$Z$$ZZ$ZZZZZZZZZOOO8MMMNZZ$$Z$$$$$$$$$$$$$Z$MMMMM. ........................
#     .+MMMMO.,,...........OMMMMMMMMMMMMMMMMMIMMMM$$ZZZZZZZZZZOOOOOOOMMMNZ$Z$$$$$$$$$$$$$ZZZMMMM,. .......................
#       MMMMM?.,,,............:MMMMMMMMMMMM=~===~MMMMZ$ZZZZZZOOOOOOOOO8NMMM$ZZ$$$$$$$$$$$$Z$8MMMM.........................
#        MMMMM.,:,,,,,,,,,,,,,,,:, DMMMMMM==Z~=~~==~MMMMZZZZOOOOOOOOOOO88NMMNZZ$$$$$$$$$$$ZZZMMMMI................... ....
#       .=MMMMM,.~:::::::::,.........,MMM=ZMMM=~~~~~==:MMMMZ$ZZOOOOOOO88888NMMZ$$Z$$$$$$$$$$$OMMMM. ......................
#     ....~MMMMMM..:~~~~.............NMMI~MMMMD~~~~~~~~~=~MMMMZZZZOOO88888888MMM$Z$$$$$$$$$$$$MMMM........................
#        . ,MMMMMMMMOIZMM+.......,,,,MMM~NMMMMZ~~~~~~~~~~==~~MMMMOZ$Z888888888DMM$ZZ$$$$$$$$$ZZMMMMO......................
#       .....MMMMM.=~:::,,,.$MMMMMMMMMMMOMMMMM~~~~~~~~~~==MMM?=~ZMMMMZZZZ8888888MMDZ$ZZ$$$$$ZZ$MMMMMMMM.  ................
#    .   ....,MMMM. ==~~~:MMMMMMMMNDDNMMMMMMMM=~~~~~~~=~~MMMMM=~~~~=MMMMMNZ$Z$ZZZMMNZ$Z$$$$$$$$NMMMMMMMMM ................
#  .  ...... .MMMMMM..,~OMMMMI=~~~~===~~==OMM~=~~~~~~~~~IMMMMM~~~~=~~==~IMMMMMMMMMMMM$Z$$$$$$$$ZM$ZZNMMMMM+...............
#       .... .7MMMMMMMMMMMMD====~~~~~~~~=~~=?M:=~~~~~~~=MMMMM7~~~~~~~~~~~~~=~=~=MN8MMM$$$$$$$$$$MZZZZZMMMMM~..............
#     .... ....OMMMMMMMMMM?~+===~~~~~~~~~~~~~=O~~=~~~~==MMMMM~~~~~~~~~~~~~~~~~=MM88DMMM$ZZ$$$$$Z$$$$$Z$8MMMM. ............
#     ...........DMMMMMMMM~++===~~~~~~~~~~~~~~~~~=~~~~=~MMMMD=~~~~~~~~~~~~~~~~MMD8888MM8ZZ$$$$$Z$$Z$ZZZ$NMMMM ............
#       .......... .MMMMM:=++====~~~~~~~~~~~~~~~~~~~~~~~MMMM=~~~~~~~~~~~~~~~=OMM888888MMZZZZ$$$$$$$ZZZO$ZMMMM ............
#       ............=MMMM==++====~~~~~~~~~~~~~~~~~~~~~==MMM~~=~~~~~~~~~~~~=~MMN8888DD8MMM$ZZ$ZZ$ZZZZZOOZZMMMM. . .........
#       .. ..........MMMM==++++===~~~~~~~~~~~~~~~~~~~~=~~=~~~~~~~~~~~~~=~8MMMD8888DDD8MMMMMMMMMMMNOOOO8ZZMMMM.............
#       .............MMMM~=?+++====~~~~~~~~~~~~~~~~~~~~~~~~~~~=~~~~~~~=~MM8D8DDDDDDD8MMM~==~==~=NMMMO88ZZMMMM ............
#     ...............MMMM?=?++++=====~~~~~~~~~~~~~~~~~~~~~=~=7MMMO~~~~~MMDDDDDDDDDD8MM~~=====++===8MMN$ZMMMM..............
#     ...............MMMMM~=??+++======~~~~~~~~~~~~~=~~~~==MMMMMMM==~~~?MM88DDDDDD8MM~=~~~~====++==~MM8MMMMM. ............
#       ..............MMMMM~=???++++==========~===~~~=8MMMMMMNNNMMZ+=~~~~MMNDDDD8MMM~=~~~=~=7OO=+++=~MMMMMM   ............
#     .................MMMMMN~~??+++++=========+MMMMMMMMMNNNNNNNMMO??~~~~+MD8D8DMMI=~~~=~MM8=====++~~NMMMN................
#       ................MMMMMMM?~~===~~~~~=~IMMNDDDDNNNNNNNNNNNNMM???~~~~~MMMMMMI~=~~~~MM7~~~~~==++==+MMM.................
#       .................MMMMMMMMMMMMMMMMMMMMMDDDDDDDNNNNNNNNNNMMM???~~~~~=~=+~==~~~=~MMMZ~~~~~===++==MMM. ...............
#        .................:MMMMMMMMMMMMMMMDDDDDDDDDDNNNNNNNNNDMMM???=~~~~~~=~~~~=~~~~=M~~~~~~~~===+==MMMM.................
#       ...................MMMMMMMNDNDDDDDDDDDDDDDNNNNNNNNNMMMM?II?I~~~~~~~~~~~~~~~~~~M=~~~~~~~===+==MMMM.................
#       ................  ..MMMMMMNNDDDDDDDDDDDDDDNNNNNNNNNM8?????+~~~~~~~~~~~~~~~~~~~MM~=~~~=~=====MMMMZ ................
#       ...................  MMMMMMNNNNNNNNNNDNNNNNNNNNNNNMM?I?=====~~~~~~~~~~~~~~~~~~==DMMD8=~==~~MMMMM, ................
#       ......................MMMMMMMMMMMNNNNNNNNNNNNNNNNMMM??I======~~~~~~~~~~~~~~~~~~~~~=~~~=~=~MMMMN. .................
#       ..................... .MMMMNNNNMMMMMMMMMMMMMMMMMMMMM???+=====~~~~~~~~~~=+~=~~~~~~~~~~==OMMMMMM..................  
#       ..................... . MMMMM$ZOMMMMMMMMMDDMMMMMOOMM??++======~~~~~~~~~MMMMMMN7+=+$NMMMMMMMM,.....................
#     ...........................MMMMM$ZOMM~~ZMMDDDOOOOOOOMM++++=======~~~~~=~MMM8OMMMMMMMMMMMMMMM,.......................
#     .... ................. .....MMMMM8ZOMM?=~MMDOOOOOOOOMM+++++==========~MMMMNNNNMMMMMMMMMMM+.. .......................
#     ............................ NMMMMM$ZMMM~=MMNOOOOOONMZ++++++======~~MMMMMMMMMMMMMMMMM:.. ...........................
#       .................... .......,MMMMM8$DMMD==MMMDOONMM??++++++==~~DMMMMMMMMMMMMMMMMMMMMMMM .. .......................
#       .................... ....... .MMMMMM$ZMMMM==NMMMMO????+?+~~~ZMMMMMMM$$ZZ$$$ZZZZ$DMMMMMMMMM........................
#       ..........OMNMMN: .  ..........8MMMMMMMMMMMMM8~==~~~~=~+MMMMMMMDMMMZ$$ZZZZZZZZZZZZ$ZOMMMMMMMM.....................
#       ... ..MMMMMMMMMMMMMM$.... ..... .MMMMMM$8MMMMMMMMMMMMMMMMMNZMMO8MMMZZZ$$$$Z$ZZZZZOOOZZ$DMMMMMMN . ................
# .   ...  .MMMMMMMMMMMMMMMMMMI. .     MMMMMMZ$MMNZ$ZZ$ZZNMMZ$$$$$$MM8888MMMM$$$Z$$$$$ZZZOOOOOOZ$ZMMMMMMMMMN.. ...........
#         MMMMMMMMMNOZO8MMMMMMMM,..OMMMMMMMM$$MMZZ$Z$$$$MMN$$$$$$$DMDOOO888NMMMNZZZ$$$ZZZZOOOOOOOZNMMMMMMMMMMM ...........
#    ...:MMMMMMMZZOZZOOOOOOMMMMMN,NMMMMMMMO$$MMZZZ$ZZZZMMZ$$$$$$$$MMOOOOO88888MMMMDZZZZZZZOOOODMMMMMM8Z8MMMMMMM?..........
#  ...MMMMMMMMZZOOOOOOOOOOOONMMMMMMMMMMMM$$$$8NMMMMMMMMM$$$$$$$$$$MMOOOOO88888888MMMM$$ZZOODMMMD.....,,:...MMMMM?.........
#  ..MMMMMMMMZOOOOOOOOOOOOOOOMMMMMMMMD,MM$$$$$$Z$$$$$Z8Z$$$$$$$$$$MMOOOOOO8888888$ZMMMMZZMMMN.........,:~=..MMMMM.........
#  .MMMMMMMMDOOOOOOOOOOOOOOOOOMMMMMM==~MMO$$$$$$$$$$NMMMMMMM$$$$$$MMZOOOOO88888888$DMMMMMM:,..............8MMMMMMMO.......
# .:MMMMM:MMOOOOOOO88888888888NMMMMZ+++MM$$$$$$$$$DMN~==~,:MMM$$$$NM8OOOOOO8888888O$MMMMM..,..................MMMMMM......
# .+MMMM=~=MNOOOO88888888888888MMMM=++=MM$$$$$$$$DM=++==+===NMM$$$$MMOOOOOOO8888888$ZMMMM.,,,...................IMMMM=....
# .+MMMMD~~MM88888888888888888DMMM8+?=MM8$$$$$$$ZM=+======+++MMO$$$ZMMZOOOOO88888888ZNMMM,DM,.....................MMMM?...
# .,MMMMM::ZMD8888888888888888MMMM?I=+MM$$$$$$$$NM+=====++??+~MN$$$$8MMOOOOO88888888ZZMMMM, ...............=M .....MMMM ..
# . MMMMM:::MM8888888888888888NMMMD==MMZ$$$$$$$$NM????????II+=MN$$$$$$MMMOO888888888MMMMM,.,................MM:....:MMMM..
#  .DMMMMM::~MD8888888888888888MMMMMMMZ$$$$$$$$$OM$IIIIIII7++MMO$$$$$$$OMMMMNDDDNMMMM8MM..,..........MM.....MMM,....MMMM..
#  ..MMMMM+:~MM8888888888888888MMMMM8$Z$$$$$$$$$$NMO777777++MMN$$$$$$$$$$$OMMMMMMNZZONM~.:,..........MMM....,MMM....MMMM..
#    8MMMMM~::MN8888888888888888MMMMZ$$$$$$$$$$$$$DMMN~++=DMMN$$$$$$$$$$$$$$ZZZZZZZOOMM.,:,...........MMM,...IMM....ZMMM..
#   ..MMMMMM:~~M8888888888888888NMMMN$$$$$$$$$$$$$$ZNMMMMMMN$$$$$$$$$$$$$$ZZZZZZZZOODMM.~:,,..........MMMM..........ZMMM..
#      MMMMMN::7M888888888888888OMMMM$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ZZZZZZZZZOOODMMM.:::,.......... OM,..........MMMM..
#     ..MMMMMM::DM888888888888888MMMMN$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ZZZZZZZZZZONMMMMMMMI.~:,~MM.................,,.,MMMM..
#       .MMMMMM~:MM888888888888888MMMMO$$$$$$$$$$$$$$$$$$$$$$$$$$ZZZZZZZZZZZOMMMMMMMMMMMD.,:,.MN..............,,:..MMMM ..
#     ....DMMMMM~:M88888888888888DMMMMM$$$$$$$$$$$$$$$$$$$$ZZZZZZZZZZZZZOOODMMMMMMOOOOMMMMMMMMMMM,.........,,,:,. MMMMN ..
#     .... MMMMM$~NM88888888888DD88MMMMMZ$ZZZZZZZZZZZZZZZZZZZZZZZZZZZOOOMMMMMMMMOO8DDDD8MMMMMMMMN+,,,,,,,,,:::..ZMMMMD....
#       .. ,MMMMM=~MM8D888DDDDDD88MMMMMMMD$ZZZZZZZZZZZZZZZZZZZZOOOOOOOOMMMMMMMMNDD88888888MMM,,~M~::::::::~,.,NMMMMM......
#    .  . . MMMMMM==MM8888DD8888MMMMMMMMMMMZ$ZZZZZZZZZOOZOOOOOOOOOOOOODMMMMOOO8M88888888888MMMM..:~~~~~~...=MMMMMMM  .....
#       ....,MMMMMM::7MMMMMMMMMMMMMMMMNMMMMMM$$$ZOOOOOOOOOOOOOOOOOOOOONMMMMDDDDMM888OOOOOOOODMMMMM$,.:8MMMMMMMMMM .  .....
#       ...  :MMMMMMMMMMMMMMMMMMMMMM+..MMMMMMMMO$$$ZOOOOOOOOOOOO888888DMMMM88888M8OOOOOOOOOOOO8MMMMMMMMMMMMMMM:...........
#     .. . . .?MMMMMMMMMMMMMMMMMMM,......MMMMMMMMMN$Z$$$OOO888888888888MMMM88888MOOOOOOOOOOOOOONM:.MMMMMMM~,..............
#       ........MMMMMMMM~$MMMMI .  ...... ,OMMMMMMMMMMM8Z$$$$$$$$$$$$$ZMMMM88888MDOOOOOOOOOOOOOOM::MMMMM ....... .........
#       ...........:..........................MMMMMMMMMMMMMMMMMMMMMMMMMMMMM88OOOMNOOOOOOOOOOOOO8MM:,MMMMO ................
#     .......................................    ,MMMMMMMMMMMMMMMMMMMMMMMMMOOOOODNOOOOOOOOOOOOOONM~:~MMMM ................
#     ...................... ...................   .. :DMMMMMMMMMMMMMMMMMMM8OOOO88OOOOOOOOOOOOOOOM,::MMMM~................
#       .................................................  .  ... .....MMMMMOOOO8OOOOOOOOOOOOOOOOMM::DMMMM................
#     ..................  .. ........................ ...  ...... ..  .MMMMMOOOOOOOOOOOOOOOOOOOO8MM:::MMMM ........... ...
#       ....................................... ... ..... ..   .. ... .?MMMMNOOOOOOOOOOOOOOOOOOOOMM::~MMMM................
#   .   ................  ........................ ......  .............MMMMMMMZOOOOOOOOOOOOOOOO8NM:::MMMM,.............  
#     ..........................................  ....  ....   ...... ...MMMMMMZOOOOOOOOOOOOOOOOO8M,::MMMM,...............
#       ......................  ...... .......  ..... .... .   .. ..  ..   MMMMZZOOOOOOOOOOOOOOOO8M7~~MMMM........... ....
#       .................... ......... .......  ... ..  ..  ..... ..... ...MMMMDZZZOOOOOOOOOOOOO88MO~=MMMM.......... .....
#       ................  . ................... .. ...... .      ... .. ...MMMMMZZZZOOOOOOOOOOOOOMMI:OMMMM ...............
#       ...................................... ... ....... ....  ... ..   .,MMMMDZZZZZZOOOOOOOOOOMM,MMMMM............ ....
#       ......................... ..............   ...  . . ..  .... .. ....MMMMM8$ZZZZZZZZZZZO8MMMMMMMMO ................
# .     ................................................. ....... ...........MMMMMMN$$$ZZZZZZDMMMMMMMMD...................
#        ...................................... .. ....... .    .... ...  . ..8MMMMMMMMMMMMMMMMMMMM+......................
#       .......................................    ...  . ......       .    ... =MMMMMMMMMMMMMMMN.. ......................
#       ........................................... . .. .. ... .....   ... .......:MMMMMMMMMZ ...........................
#     ..................      ... ............  ... .   . .       .. .. ...     . ....... .. .  ......... ....   ...  ....



require 'uuidtools'
require 'base64'


class Map < ActiveRecord::Base
  include ActionView::Helpers::TextHelper

  MAX_TEXT_RENDER_LEN = 260
  MAX_NAME_RENDER_LEN = 100

  # Core components	
  attr_accessible :name, :slug, :text, :thumbnail, :user_id

  # For quick rendering of item counts
  attr_accessible :resources_count, :standards_count, :objectives_count

  has_and_belongs_to_many :course_subjects, uniq: true, order: 'name ASC'
  has_and_belongs_to_many :course_grades, uniq: true, order: 'id ASC'
  
  has_many :map_standards, dependent: :destroy
  has_many :map_assessments, dependent: :destroy

  belongs_to :user

  validates :user, presence: true
  validates :name, length: {minimum: 2, maximum: 250}
  validates :text, length: {minimum: 2, maximum: 2048}
  validates_uniqueness_of :slug, allow_nil: true, case_sensitive: true

  after_initialize :default_values
  before_validation	:clean_attrs

  def title_titlecase
    self.name.titlecase
  end

  def sorted_map_standards
    # Sorts by standards
    self.map_standards.all(:order => :standard_id)
  end

  def update_metadata
    self.map_standards.each do |map_standard|
      self.course_grades << map_standard.standard.course_grades
      self.course_subjects << map_standard.standard.course_subject
    end
  end

  def course_grade_ranges


    return '' if self.course_grades.empty?

    grades = self.course_grades.map do |grade|
      if grade.name == 'K'
        0
      else 
        Integer(grade.name)
      end
    end

    ranges = grades.sort.uniq.inject([]) do |spans, n|
      Rails.logger.info("#{spans} #{n}")
      if spans.empty? || spans.last.last.succ != n
        Rails.logger.info("\t#{spans.last} #{n}")
        spans + [n..n]
      else
        spans[0..-2] + [spans.last.first..n]
      end
    end

    Rails.logger.info(ranges)
    result = []
    ranges.each do |range|
      if range.first != range.last
        result << "#{range.first}&mdash;#{range.last}"
      elsif range.first == range.last and range.first
        result << "#{range.first}"
      end
    end

    result.join(', ').sub('0', 'K')
  end

  private 

  def clean_attrs
    default_values
    self.name = self.name.strip
    self.text = self.text.strip
  end

  def default_values
    self.slug ||= (Base64.strict_encode64 UUIDTools::UUID.random_create).downcase
    
    self.name ||= 'New Untitled Map'  
    self.text ||= 'Description of the Map'
    self.resources_count  ||= 0
    self.standards_count  ||= 0
    self.objectives_count ||= 0
  end
  
end

